import discord

def get_guild_vars(guild):
    """Get all guild-related variables"""
    return {
        "{guild.name}": guild.name,
        "{guild.id}": str(guild.id),
        "{guild.created_at}": discord.utils.format_dt(guild.created_at, style="f"),
        "{guild.created_at_timestamp}": str(int(guild.created_at.timestamp())),
        "{guild.owner}": guild.owner.name,
        "{guild.owner_id}": str(guild.owner_id),
        "{guild.owner_mention}": guild.owner.mention,
        "{guild.member_count}": str(guild.member_count),
        "{guild.boosts}": str(guild.premium_subscription_count),
        "{guild.boost_level}": str(guild.premium_tier),
        "{guild.verification_level}": str(guild.verification_level).replace("VerificationLevel.", ""),
        "{guild.explicit_content_filter}": str(guild.explicit_content_filter).replace("ContentFilter.", ""),
        "{guild.afk_channel}": guild.afk_channel.name if guild.afk_channel else "None",
        "{guild.afk_timeout}": str(guild.afk_timeout),
        "{guild.system_channel}": guild.system_channel.name if guild.system_channel else "None",
        "{guild.rules_channel}": guild.rules_channel.name if guild.rules_channel else "None",
        "{guild.public_updates_channel}": guild.public_updates_channel.name if guild.public_updates_channel else "None",
        "{guild.icon}": str(guild.icon.url) if guild.icon else "None",
        "{guild.banner}": str(guild.banner.url) if guild.banner else "None",
        "{guild.splash}": str(guild.splash.url) if guild.splash else "None",
        "{guild.description}": guild.description if guild.description else "None",
        "{guild.features}": ", ".join(guild.features) if guild.features else "None",
        "{guild.vanity_url}": guild.vanity_url_code if guild.vanity_url_code else "None",
        "{guild.preferred_locale}": guild.preferred_locale,
        "{guild.mfa_level}": str(guild.mfa_level),
        "{guild.nsfw_level}": str(guild.nsfw_level).replace("NSFWLevel.", ""),
        "{guild.count}": str(guild.member_count),
        "{guild.emoji_count}": str(len(guild.emojis)),
        "{guild.role_count}": str(len(guild.roles)),
        "{guild.max_presences}": str(guild.max_presences),
        "{guild.max_members}": str(guild.max_members),
        "{guild.max_video_channel_users}": str(guild.max_video_channel_users),
        "{guild.channels}": ", ".join([channel.mention for channel in guild.channels]),
        "{guild.channels_count}": str(len(guild.channels)),
        "{guild.text_channels}": ", ".join([channel.mention for channel in guild.text_channels]),
        "{guild.text_channels_count}": str(len(guild.text_channels)),
        "{guild.voice_channels}": ", ".join([channel.mention for channel in guild.voice_channels]),
        "{guild.voice_channels_count}": str(len(guild.voice_channels)),
        "{guild.category_channels}": ", ".join([channel.mention for channel in guild.categories]),
        "{guild.category_channels_count}": str(len(guild.categories))
    } 